export const GET_ALL_POST_REQUEST = 'GET_ALL_POST_REQUEST';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_FAILED = 'GET_ALL_POSTS_FAILED';

// export const GET_MY_POSTS_SUCCESS = 'GET_MY_POSTS_SUCCESS';
// export const GET_MY_POSTS_FAILED = 'GET_MY_POSTS_FAILED';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const CREATE_POST = 'CREATE_POST';
export const DELETE_POST = 'DELETE_POST';
