export const GET_DETAILED_USER_INFO_REQUEST = 'GET_DETAILED_USER_INFO_REQUEST';
export const GET_DETAILED_USER_INFO_SUCCESS = 'GET_DETAILED_USER_INFO_SUCCESS';
export const GET_DETAILED_USER_INFO_FAILED = 'GET_DETAILED_USER_INFO_FAILED';

export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const UPLOAD_PROFILE_IMG = 'UPLOAD_PROFILE_IMG';
